version: '3.8'

services:
  web:
    build: .
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: